import { vpc } from "./vpc";

/**
 * RDS Postgres — the single application database (app tables + Better Auth
 * tables live together; modular-monolith MVP).
 *
 * Smallest sensible footprint: `db.t4g.micro` + 20 GB gp3. SST's defaults
 * match this, but we pin them explicitly so a future SST default-bump can't
 * silently resize the instance. `proxy: false` — RDS Proxy is ~$11/mo
 * minimum and our Lambda concurrency at MVP traffic won't exhaust
 * connections; revisit alongside the `nat: "managed"` production hardening.
 */
export const postgres = new sst.aws.Postgres("Postgres", {
  vpc,
  instance: "t4g.micro",
  storage: "20 GB",
  proxy: false,
});

/**
 * Connection string consumed as `POSTGRES_URL` by:
 *  - `packages/db/src/client.ts` (Drizzle client, runtime)
 *  - `packages/db/drizzle.config.ts` (`pnpm db:push`, via `npx sst tunnel`)
 *
 * The password is generated by RDS and may contain URL-reserved characters,
 * hence the explicit `encodeURIComponent`. No `sslmode` pin here: RDS
 * negotiates TLS by default and pinning `sslmode=require` trips strict CA
 * verification in some clients without the RDS CA bundle — see the runbook
 * note in infra/README.md.
 */
export const postgresUrl = $resolve([
  postgres.username,
  postgres.password,
  postgres.host,
  postgres.port,
  postgres.database,
]).apply(
  ([username, password, host, port, database]) =>
    `postgres://${username}:${encodeURIComponent(password)}@${host}:${port}/${database}`,
);
